[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && npx prisma db push --accept-data-loss --skip-generate && npx tsx prisma/seed.ts"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
